In [5]:
import numpy as np


def main():
    array = np.random.randint(1,101,(5,5))
    print("Random Array:")
    print(array)
    
    middle_element = array[2,2]
    print(f"Middle Element of Array: {middle_element}")
    
    overall_mean = np.mean(array)
    row_mean = np.mean(array, axis=1)
    
    print (f"Row mean of array: {row_mean}")
    print (f"Overall mean of array: {overall_mean}")
    
    greater_than_mean = array[array > overall_mean]
    print(f"Array with elements greater than overall mean:{greater_than_mean}")

    sprial_arr = numpy_spiral_order(array)
    print("Array in Spiral order:")
    print (sprial_arr)

def numpy_spiral_order(matrix):
    spiral_array=[]
    rows, columns= matrix.shape
    top, bottom, left, right = 0, rows - 1, 0, columns - 1

    while top <= bottom and left <= right:

        for columns in range(left, right + 1):
            spiral_array.append(matrix[top, columns])
        top += 1
        
        for row in range(top, bottom + 1):
            spiral_array.append(matrix[row, right])
        right -= 1
        
        for columns in range(right, left - 1, -1):
            spiral_array.append(matrix[bottom, columns])
        bottom -= 1
        
        for row in range(bottom, top - 1, -1):
            spiral_array.append(matrix[row, left])
        left += 1
     
    return spiral_array         

        
if __name__ == "__main__":
    main()

Random Array:
[[55 75 44 57 65]
 [81 65 79 16 61]
 [85 51 87 52 97]
 [76 44 51 90 40]
 [68 12 98 94 26]]
Middle Element of Array: 87
Row mean of array: [59.2 60.4 74.4 60.2 59.6]
Overall mean of array: 62.76
Array with elements greater than overall mean:[75 65 81 65 79 85 87 97 76 90 68 98 94]
Array in Spiral order:
[55, 75, 44, 57, 65, 61, 97, 40, 26, 94, 98, 12, 68, 76, 85, 81, 65, 79, 16, 52, 90, 51, 44, 51, 87]
